@@grammar :: TextGrammar

@@whitespace :: ?"[\t ]+"

@@eol_comments :: ?"^(#.*|\s*)\n"


symbol = ?"[\w()/!<>-]+" ;

literal = ?"(([^;|<>\n\[\]()]|\[[^\[\]]*\]|\([^()]*\))+(?<!\s))?" ;

adjectiveNoun::AdjectiveNoun = adjective:literal "|" noun:literal ;

entityName = adjectiveNoun | literal;

match::Match = lhs:entityName "<->" rhs:entityName ;

alternative = match | entityName;

alternatives = ";".{alternative}+ ;

productionRule::ProductionRule = symbol:symbol ":" alternatives:alternatives ("\n" | $) ;

grammar::TextGrammar = rules:{productionRule}* $ ;

start = grammar ;
