# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    sudo apt update && sudo apt install -y --no-install-recommends chromium-chromedriver graphviz
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    ./.azure/scripts/setup.sh
  displayName: 'Install TextWorld'

- script: |
    ./.azure/scripts/test.sh
    for i in {1..5}; do codecov --required && break || sleep 30; done
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)
  displayName: 'Run tests and coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'nosetests.xml'
    testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python 3.7'
