jobs:
  - ${{ each vmImage in parameters.vmImages }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job:
          displayName: ${{ format('OS:{0} PY:{1}', vmImage, pythonVersion) }}
          pool:
            vmImage: ${{ vmImage }}

          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '${{ pythonVersion }}'

          - script: |
              sudo apt update && sudo apt install -y --no-install-recommends graphviz
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              ./.travis/setup.sh
            displayName: 'Install TextWorld'

          - script: |
              ./.travis/test.sh
            displayName: 'Run tests'
