jobs:
  - ${{ each vmImage in parameters.vmImages }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job:
          displayName: ${{ format('OS:{0} PY:{1}', vmImage, pythonVersion) }}
          pool:
            vmImage: ${{ vmImage }}

          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '${{ pythonVersion }}'

          - script: |
              brew install graphviz
              pip install nose coverage codecov wheel
            displayName: 'Install dependencies'

          - script: |
              pip install "textworld[full]>=.dev"
            condition: eq(variables.installFromSource, false)
            displayName: 'Install a prerelease of TextWorld from PyPi'

          - script: |
              pip install -r requirements-full.txt
              pip install .
            condition: eq(variables.installFromSource, true)
            displayName: 'Install TextWorld from source'

          - script: |
              nosetests -sv --with-xunit --with-coverage --cover-xml --cover-html --cover-package textworld
            displayName: 'Run tests'
