# Release code in the main branch to PyPi as a release candidate

stages:
- stage: Prerelease_on_PyPi
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python'

    - script: |
        pip install twine

    # Build the python distribution from source
    - script: |
        pip install -r requirements.txt
        TEXTWORLD_PRERELEASE=true ./tools/package.sh

    - task: TwineAuthenticate@1
      displayName: 'Twine Authenticate'
      inputs:
        pythonUploadServiceConnection: pypi

    # Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
    - script: |
        python -m twine upload -r pypi --config-file $(PYPIRC_PATH) dist/textworld-*

- stage: Test_library
  variables:
  - name: installFromSource
    value: false
    readonly: true
  jobs:
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-20.04' ]
      pythonVersions: [ '3.9' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-latest' ]
      pythonVersions: [ '3.12' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-11' ]
      pythonVersions: [ '3.9' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-latest' ]
      pythonVersions: [ '3.12' ]