# Release code in the main branch to PyPi

jobs:
- job:
  displayName: Release_on_PyPi
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python'

  - script: |
      pip install twine

  # Build the python distribution from source
  - script: |
      pip install -r requirements.txt
      ./tools/package.sh

  - task: TwineAuthenticate@1
    displayName: 'Twine Authenticate'
    inputs:
      pythonUploadServiceConnection: pypi

  # Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
  - script: |
      python -m twine upload -r pypi --config-file $(PYPIRC_PATH) dist/textworld-*
