trigger:
- master

stages:
- stage: Test
  variables:
  - name: installFromSource
    value: true
    readonly: true
  jobs:
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-18.04' ]
      pythonVersions: [ '3.7' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-latest' ]
      pythonVersions: [ '3.8' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-10.15' ]
      pythonVersions: [ '3.7' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-latest' ]
      pythonVersions: [ '3.9' ]
