trigger:
- master

stages:
- stage: Test
  variables:
  - name: installFromSource
    value: true
    readonly: true
  jobs:
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-18.04' ]
      pythonVersions: [ '3.7', '3.8' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-20.04' ]
      pythonVersions: [ '3.7', '3.8' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-10.14' ]
      pythonVersions: [ '3.6' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-10.15' ]
      pythonVersions: [ '3.7' ]
      # pythonVersions: [ '3.8' ]  # For some reasons, chromedriver is failing.
