trigger:
- main

stages:
- stage: Test
  variables:
  - name: installFromSource
    value: true
    readonly: true
  jobs:
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-20.04' ]
      pythonVersions: [ '3.8' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-latest' ]
      pythonVersions: [ '3.9' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-latest' ]
      pythonVersions: [ '3.10' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-latest' ]
      pythonVersions: [ '3.11' ]
  - template: linux-template.yml
    parameters:
      vmImages: [ 'ubuntu-latest' ]
      pythonVersions: [ '3.12' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-latest' ]
      pythonVersions: [ '3.9' ]
  - template: macos-template.yml
    parameters:
      vmImages: [ 'macOS-latest' ]
      pythonVersions: [ '3.10' ]
