.\" -*- nroff -*-
.TH DFROTZ 6 2.45pre
.SH NAME
dfrotz \- interpreter for Infocom and other Z-Machine games (dumb interface)

.SH SYNOPSIS
.B dfrotz
.RI [ options "] " file

.SH DESCRIPTION
.B Frotz
is a Z-Machine interpreter.  The Z-machine is a virtual machine designed
by Infocom to run all of their text adventures.  It went through multiple
revisions during the lifetime of the company, and two further revisions
(V7 and V8) were created by Graham Nelson after the company's demise.
The specification is now quite well documented; this version of Frotz
supports version 1.0.
.P
This version of Frotz fully supports all these versions of the Z-Machine
except for version 6.  Version 6 is semi-supported by displaying the
outlines of V6 graphics with the picture number in the bottom-right
corner.

.P
This manpage is for Frotz with the dumb interface.  Dumb Frotz 
does not support sound-effects, graphics, or colors.


.SH OPTIONS
.TP
.B \-a
Watch attribute setting.  Setting and clearing of attributes on objects
will be noted in debugging messages.

.TP
.B \-A
Watch attribute testing.  Every time the z-machine tests an attribute
value, the test and the result will be reported.

.TP
.B \-h N
Screen height.  Every N lines, a MORE prompt will be printed.  Use of 
the
.B \-m
option renders this option moot.

.TP
.B \-i
Ignore fatal errors.  If a Z-Machine interpreter encounters a zcode error
such as division-by-zero or addressing an illegal object, the proper
response is to abort execution.  This is done because the zcode program
doesn't have a clear idea of what is going on.  There are some games out
there that cause fatal errors because the authors were careless and used
an interpreter that didn't properly check for errors.  This option is
intended to get around such bugs, but be warned that Strange Things may
happen if fatal errors are not caught.

.TP
.B \-L <filename>
When the game starts, load this saved game file.

.TP
.B \-m
Turn off MORE prompts.  This can be desirable when using a printing 
terminal.

.TP
.B \-o
Watch object movement.  This option enables debugging messages from the
interpreter which describe the moving of objects in the object tree.

.TP
.B \-O
Watch object location.  These debugging messages detail the locations of
objects in the object tree.

.TP
.B \-p
Plain ASCII output only.  This inhibits the output of accented letters
and other characters from the Latin-1 character set, replacing them with
reasonable alternatives.  This may be necessary on devices lacking these
characters.

.TP
.B \-P
Alter the piracy opcode.  The piracy opcode was never used by Infocom.
This switch is really only useful for those who like to toy around with
Z-code.

.TP
.B \-r \exxx
Set runtime options.  This option may be used repeatedly.

.TP
.B \-R <path>
Restricted read/write.  Reading and writing files will be restricted
only to the provided path. Ordinarily Frotz will write or read its
saves, transcripts, and move recordings in whatever path or directory
the user provides when the
.B SAVE,
.B SCRIPT,
or
.B RECORDING
commands are given.  This can be undesirable if Frotz is run in a
restricted environment, by a front end, or by a chatbot.  This option will
cause Frotz to write or read only to the provided path and nowhere else.
Then the controlling process can then watch that directory for changes
and need not worry about someone scribbling or snooping who-knows-where.

.TP
.B \-s N
Set the random number seed value.  The given seed value is used as the initial
seed value on every restart. This is helpful for testing games like
.B Curses
which make random decisions before the first input (such that the hot
key Alt\-S does not really help).

.TP
.B \-S N
Set the transcript width.  By default your transscript files are formatted
to a width of 80 columns per line, regardless of the current screen width.
This switch allows you to change this setting. In particular, use \-S 0
to deactivate automatic line splitting in transscript files.

.TP
.B \-t
Sets the z-machine's
.I Tandy bit,
which may affect the behavior of certain Infocom games.  For example,
Zork I pretends not to have sequels, and Witness has its language
toned down.

.TP
.B \-u N
Sets the number of slots available for Frotz's multiple undo hotkey (see
below).  This defaults to twenty, which should be sufficient for most
purposes.  Setting too high a number here may be dangerous on machines
with limited memory.

.TP
.B \-w N
Manually sets the screen width.  This should not be necessary except in
special circumstances.

.TP
.B \-x
Expand the abbreviations "g", "x", and "z" to "again", "examine", and
"wait".  This switch is for use iwth old Infocom games that lack these
common abbreviations which were introduced in later games.  Use it with
caution: A few games might use "g", "x" or "z" for different purposes.

.TP
.B \-Z N
Error checking mode.
.br
0 = don't report errors.
.br
1 = report first instance of an error.
.br
2 = report all errors.
.br
3 = exit after any error.
.br
Default is 1 (report first instance of an error).


.SH CONFIGURATION
Unlike it's curses-using sibling,
.B dfrotz
does not use configuration files.  All configuration is done on the
command line or while
.B dfrotz
is running.
.P

.SS General Commands

.TP
.B \ehelp
Show help message.
.TP
.B \eset
Show the current values of runtime settings.
.TP
.B \es
Show the current contents of the whole screen.
.TP
.B \ed
Discard the part of the input before the cursor.
.TP
.B \ewN
Advance clock N/10 seconds, possibly causing the current and subsequent
inputs to timeout.
.TP
.B \ew
Advance clock by the amount of real time since this input started (times
the current speed factor).
.TP
.B \et
Advance clock just enough to timeout the current input

.SS Reverse-Video Display Method Settings

.TP
.B \ern
none
.TP
.B \erc
CAPS
.TP
.B \erd
doublestrike
.TP
.B \eru
underline

.SS Output Compression Settings

.TP
.B \ecn
none: show whole screen before every input.
.TP
.B \ecm
max: show only lines that have new nonblank characters.
.TP
.B \ecs
spans: like max, but emit a blank line between each span of screen lines
shown.
.TP
.B \echN
Hide top N lines (orthogonal to above modes).

.SS Misc Settings

.TP
.B \esfX
Set speed factor to X.  (0 = never timeout automatically).
.TP
.B \emp
Toggle use of MORE prompts
.TP
.B \eln
Toggle display of line numbers.
.TP
.B \elt
Toggle display of the line type identification chars.
.TP
.B \evb
Toggle visual bell.
.TP
.B \epb
Toggle display of picture outline boxes.
.TP
(Toggle commands can be followed by a 1 or 0 to set value ON or OFF.)

.SS Character Escapes
.TP
.B \e\e
backslash
.TP
.B \e#
backspace
.TP
.B \e[
escape
.TP
.B \e_
return
.TP
.B \e<
cursor-left
.TP
.B \e>
cursor-right
.TP
.B \e^
cursor-up
.TP
.B \e.
cursor-down
.TP
.B \e1..\e0
f1..f10
.TP
.B \eD..\eX
Standard Frotz hotkeys.
.TP
use \eH (help) to see the list of hotkeys.

.SS Line Type Identification Characters

.SS Input lines (untimed)
.TP
.B >
A regular line-oriented input
.TP
.B )
A single-character input
.TP
.B }
A line input with some input before the cursor.  Use \ed to discard it.
.SS Input lines (timed)
.TP
.B T
A regular line-oriented input
.TP
.B t
A single-character input
.TP
.B D
A line input with some input before the cursor.  Use \ed to discard it.
.SS Output lines
.TP
.B ]
Output line that contains the cursor.
.TP
.B .
A blank line emitted as part of span compression.
.TP
.B \~
(blank) Any other output line.


.SH ENVIRONMENT
Unlike it's curses-using sibling,
.B dfrotz
does not search any path for game files.


.SH FURTHER INFORMATION
.PP
A
.BR git(1)
repository of all versions of Unix Frotz back to 2.32 is available 
for public perusal here:
.br
https://github.com/DavidGriffith/frotz/. 
.PP
The bleeding edge of Frotz development may be followed there.  A wiki 
summarising Frotz is also there at this URL:
.br
https://github.com/DavidGriffith/frotz/wiki/
.PP
Source tarballs are available at the IF Archive or any of its many 
mirrors:
.br
http://www.ifarchive.org/
.PP
Most distributions of Linux and BSD include Frotz in their package 
repositories.


.SH CAVEATS
.PP
The Z Machine itself has trouble with the concept of resizing a terminal.
It assumes that once the screen height and width are set, they will never
change; even across saves.  This made sense when 24x80 terminals were the
norm and graphical user interfaces were mostly unknown.  I'm fairly sure
there's a way around this problem, but for now, don't resize an xterm in
which frotz is running.  Also, you should try to make sure the terminal
on which you restore a saved game has the same dimensions as the one on
which you saved the game.

.PP
This manpage is not intended to tell users HOW to play interactive
fiction.  Refer to the file HOW_TO_PLAY included in the Unix Frotz
documentation or visit one of the following sites:
.br
http://www.microheaven.com/ifguide/
.br
http://www.brasslantern.org/beginners/
.br
http://www.musicwords.net/if/how_to_play.htm
.br
http://ifarchive.org/

.PP
If you prefer a PDF file of how to play, here is one:
.br
http://inform-fiction.org/I7Downloads/Examples/dm/IntroductionToIF.pdf


.SH BUGS
This program has no bugs.  no bugs.  no bugs.  no *WHAP* thank you. If 
you find one, please report it to the Github site referenced above in
.B
FURTHER INFORMATION.


.SH AUTHORS
.B Frotz
was written by Stefan Jokisch for MSDOS in 1995-7.
.br
The Unix port was done by Galen Hazelwood.
.br
The Unix port is currently maintained by David Griffith <dave@661.org>.


.SH "SEE ALSO"
.BR frotz (6)
.BR nitfol (6)
.BR rezrov (6)
.BR jzip (6)
.BR xzip (6)
.BR inform (1)


